"""add user.password_hash

Revision ID: fee03dd51a26
Revises: 1f8dbae4ab2a
Create Date: 2026-06-23 12:31:40.635024

"""
# from email.mime import text
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from passlib.context import CryptContext
from sqlalchemy import text
from app.auth.hashing import hash_password

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


# revision identifiers, used by Alembic.
revision: str = 'fee03dd51a26'
down_revision: Union[str, Sequence[str], None] = '1f8dbae4ab2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column('password_hash', sa.String(length=200), nullable=True))
    op.create_unique_constraint("unique_user_name", 'users', ['name'])
    # ### end Alembic commands ###
    default_hash = hash_password("password123")

    op.execute(
        # text("UPDATE users SET password_hash = :h").bindparams(h=default_hash)
        f"UPDATE users SET password_hash = '{default_hash}'"
    )

    op.alter_column("users", "password_hash", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_user_name", 'users', type_='unique')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
