"""add user.password_hash

Revision ID: 2743840046ee
Revises: 4f85593a3d02
Create Date: 2026-06-23 12:58:13.586962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from passlib.context import CryptContext

pwd = CryptContext(schemes=["bcrypt"], deprecated="auto")

# revision identifiers, used by Alembic.
revision: str = '2743840046ee'
down_revision: Union[str, Sequence[str], None] = '4f85593a3d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=200), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['name'])
    default_password = pwd.hash("pass123")
    op.execute(
        sa.text("UPDATE users SET password_hash = :h").bindparams(h=default_password)
    )
    # Step 3: every row now has a value, so it's safe to lock the column down.
    op.alter_column('users', 'password_hash', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
