"""add user.password_hash

Revision ID: 31c0efe927d2
Revises: 50242cf2c30b
Create Date: 2026-06-23 13:12:08.808230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from passlib.context import CryptContext
from sqlalchemy import text
from app.auth.hashing import hash_password

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


# revision identifiers, used by Alembic.
revision: str = '31c0efe927d2'
down_revision: Union[str, Sequence[str], None] = '50242cf2c30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=200), nullable=True))
    op.create_unique_constraint("unique_users_name", 'users', ['name'])
    # ### end Alembic commands ###
    default_hash = hash_password("password123")

    op.execute(
        # text("UPDATE users SET password_hash = :h").bindparams(h=default_hash)
        f"UPDATE users SET password_hash = '{default_hash}'"
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_users_name", 'users', type_='unique')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###